/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aditya
 */
public class Other extends javax.swing.JFrame {

    /**
     * Creates new form Other
     */
    public Other() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mfg_date = new javax.swing.JTextField();
        sample = new javax.swing.JButton();
        q_update = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Owner1 = new javax.swing.JLabel();
        Owner = new javax.swing.JLabel();
        exp_date = new javax.swing.JTextField();
        ID1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        m_id1 = new javax.swing.JTextField();
        ID2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_medical = new javax.swing.JTable();
        m_name = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        m_cost = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        status_final = new javax.swing.JTextArea();
        ID = new javax.swing.JLabel();
        m_type = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        m_id = new javax.swing.JTextField();
        p_update = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sample.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        sample.setText("Other Info");
        sample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Other Cost");

        Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Address.setText("Other Type");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Column Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("New Value");

        Owner1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Owner1.setText("Exp Date");

        Owner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Owner.setText("MFG Date");

        exp_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp_dateActionPerformed(evt);
            }
        });

        ID1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID1.setText("Other ID");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ID2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID2.setText("Other Name");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        T_medical.setBackground(new java.awt.Color(204, 204, 255));
        T_medical.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        T_medical.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        T_medical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Other ID", "Other Name", "Other Cost", "Other Type", "MFG Date", "EXP Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        T_medical.setToolTipText("");
        T_medical.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T_medical.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        T_medical.setDropMode(javax.swing.DropMode.ON);
        T_medical.setSelectionBackground(new java.awt.Color(0, 0, 0));
        T_medical.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(T_medical);

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset All");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        m_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_costActionPerformed(evt);
            }
        });

        status_final.setColumns(20);
        status_final.setRows(5);
        jScrollPane2.setViewportView(status_final);

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Other ID");

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(mfg_date))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Address)
                                .addGap(148, 148, 148)
                                .addComponent(m_type))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ID2)
                                .addGap(138, 138, 138)
                                .addComponent(m_name))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Owner1)
                                        .addGap(167, 167, 167)
                                        .addComponent(exp_date, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Owner)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Name)
                                        .addGap(152, 152, 152)
                                        .addComponent(m_cost)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ID)
                                .addGap(164, 164, 164)
                                .addComponent(m_id)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(ID1)
                                    .addComponent(jLabel2))
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q_update, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(p_update, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(m_id1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(619, 619, 619)
                                .addComponent(sample))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(reset)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID)
                            .addComponent(m_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_type, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mfg_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Owner))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exp_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Owner1))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sample)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(q_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ID1)
                                .addComponent(m_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleActionPerformed
        try{

            T_medical.setModel(new DefaultTableModel(
                new Object [][] {

                }, new String [] {"Other ID","Other Name", "Other Cost", "Other Type", "MFG Date","EXP Date"}
            ));

            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

            Statement st = cn.createStatement();
            String qurry = "select * from other";
            ResultSet rs = st.executeQuery(qurry);

            while(rs.next()){
                String m_id = String.valueOf(rs.getInt("o_id"));
                String m_name = String.valueOf(rs.getString("o_name"));
                String m_cost = String.valueOf(rs.getFloat("o_cost"));

                String med_type = String.valueOf(rs.getString("o_type"));
                String mfg_date = String.valueOf(rs.getString("o_mfg_date"));
                String exp_date = String.valueOf(rs.getString("o_exp_date"));

                String TBdata[] = {m_id,m_name,m_cost,med_type,mfg_date,exp_date};
                DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                tb1Model.addRow(TBdata);

            }

        }

        catch(Exception e){

            System.out.print(e);
        }
    }//GEN-LAST:event_sampleActionPerformed

    private void exp_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exp_dateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{

            int a = Integer.parseInt(m_id.getText());
            String b = m_name.getText();
            int c = Integer.parseInt(m_cost.getText());

            String d = m_type.getText();
            String e = mfg_date.getText();
            String f = exp_date.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

            Statement st = cn.createStatement();
            st.executeUpdate("insert into other values("+a+",'"+b+"',"+c+",'"+d+"','"+e+"','"+f+"')");

            m_id.setText(null);
            m_cost.setText(null);
            m_type.setText(null);
            mfg_date.setText(null);
            exp_date.setText(null);

            m_name.setText(null);

            status_final.setText("Inserted");

            T_medical.setModel(new DefaultTableModel(
                new Object [][] {

                }, new String [] {"Other ID","Other Name", "Other Cost", "Other Type", "MFG Date","EXP Date"}
            ));

            Statement st1 = cn.createStatement();
            String qurry = "select * from other";
            ResultSet rs = st1.executeQuery(qurry);

            while(rs.next()){
                String m_id = String.valueOf(rs.getInt("o_id"));
                String m_name = String.valueOf(rs.getString("o_name"));
                String m_cost = String.valueOf(rs.getFloat("o_cost"));

                String med_type = String.valueOf(rs.getString("o_type"));
                String mfg_date = String.valueOf(rs.getString("o_mfg_date"));
                String exp_date = String.valueOf(rs.getString("o_exp_date"));

                String TBdata[] = {m_id,m_name,m_cost,med_type,mfg_date,exp_date};
                DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                tb1Model.addRow(TBdata);
            }
            st1.close();

        }

        catch(Exception e){

            status_final.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            int r = Integer.parseInt(m_id.getText());
            String n = m_cost.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

            Statement st = cn.createStatement();
            st.executeUpdate("delete from other where o_id="+r+"");

            m_id.setText(null);
            m_cost.setText(null);
            m_type.setText(null);
            mfg_date.setText(null);
            exp_date.setText(null);

            m_name.setText(null);

            status_final.setText("Deleted");

            T_medical.setModel(new DefaultTableModel(
                new Object [][] {

                }, new String [] {"Other ID","Other Name", "Other Cost", "Other Type", "MFG Date","EXP Date"}
            ));

            Statement st1 = cn.createStatement();
            String qurry = "select * from other";
            ResultSet rs = st1.executeQuery(qurry);

            while(rs.next()){
                String m_id = String.valueOf(rs.getInt("o_id"));
                String m_name = String.valueOf(rs.getString("o_name"));
                String m_cost = String.valueOf(rs.getFloat("o_cost"));

                String med_type = String.valueOf(rs.getString("o_type"));
                String mfg_date = String.valueOf(rs.getString("o_mfg_date"));
                String exp_date = String.valueOf(rs.getString("o_exp_date"));

                String TBdata[] = {m_id,m_name,m_cost,med_type,mfg_date,exp_date};
                DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                tb1Model.addRow(TBdata);
            }
            st1.close();

        }

        catch(Exception e){

            status_final.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        m_id.setText(null);
        m_cost.setText(null);
        m_type.setText(null);
        mfg_date.setText(null);
        exp_date.setText(null);

        m_name.setText(null);
        m_id1.setText(null);
        p_update.setText(null);
        q_update.setText(null);

        status_final.setText(null);

        T_medical.setModel(new DefaultTableModel(
            new Object [][] {

            }, new String [] {"Other ID","Other Name", "Other Cost", "Other Type", "MFG Date","EXP Date"}
        ));
    }//GEN-LAST:event_resetActionPerformed

    private void m_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_costActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            int r = Integer.parseInt(m_id1.getText());
            String p = p_update.getText();
            String q = q_update.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

            Statement st = cn.createStatement();
            st.executeUpdate("update other set "+p+"='"+q+"' where o_id="+r+"");
            m_id1.setText(null);
            p_update.setText(null);
            q_update.setText(null);

            status_final.setText("Updated");

            T_medical.setModel(new DefaultTableModel(
                new Object [][] {

                }, new String [] {"Other ID","Other Name", "Other Cost", "Other Type", "MFG Date","EXP Date"}
            ));

            Statement st1 = cn.createStatement();
            String qurry = "select * from other";
            ResultSet rs = st1.executeQuery(qurry);

            while(rs.next()){
                String m_id = String.valueOf(rs.getInt("o_id"));
                String m_name = String.valueOf(rs.getString("o_name"));
                String m_cost = String.valueOf(rs.getFloat("o_cost"));

                String med_type = String.valueOf(rs.getString("o_type"));
                String mfg_date = String.valueOf(rs.getString("o_mfg_date"));
                String exp_date = String.valueOf(rs.getString("o_exp_date"));

                String TBdata[] = {m_id,m_name,m_cost,med_type,mfg_date,exp_date};
                DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                tb1Model.addRow(TBdata);
            }
            st1.close();

        }

        catch(Exception e){

            status_final.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Other().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel ID2;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Owner;
    private javax.swing.JLabel Owner1;
    private javax.swing.JTable T_medical;
    private javax.swing.JTextField exp_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField m_cost;
    private javax.swing.JTextField m_id;
    private javax.swing.JTextField m_id1;
    private javax.swing.JTextField m_name;
    private javax.swing.JTextField m_type;
    private javax.swing.JTextField mfg_date;
    private javax.swing.JTextField p_update;
    private javax.swing.JTextField q_update;
    private javax.swing.JButton reset;
    private javax.swing.JButton sample;
    private javax.swing.JTextArea status_final;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
