/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aditya
 */
public class StaffInfo extends javax.swing.JFrame {

    /**
     * Creates new form StaffInfo
     */
    public StaffInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Owner = new javax.swing.JLabel();
        ID1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        staff_id1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        status_final = new javax.swing.JTextArea();
        update = new javax.swing.JButton();
        p_update = new javax.swing.JTextField();
        sample = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_medical = new javax.swing.JTable();
        staff_name = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        staff_gender = new javax.swing.JTextField();
        staff_id = new javax.swing.JTextField();
        staff_mobile = new javax.swing.JTextField();
        q_update = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Owner1 = new javax.swing.JLabel();
        staff_mail = new javax.swing.JTextField();
        Owner2 = new javax.swing.JLabel();
        staff_address = new javax.swing.JTextField();
        ID2 = new javax.swing.JLabel();
        medical_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Address.setText("Staff Gender");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("New Value");

        Owner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Owner.setText("Staff Mobile");

        ID1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID1.setText("Staff ID");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset All");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        status_final.setColumns(20);
        status_final.setRows(5);
        jScrollPane2.setViewportView(status_final);

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        sample.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        sample.setText("Staff Info");
        sample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleActionPerformed(evt);
            }
        });

        T_medical.setBackground(new java.awt.Color(204, 204, 255));
        T_medical.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        T_medical.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        T_medical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "staff_id", "medical_id", "staff_name", "staff_gender", "staff_mobile", "staff_mail", "staff_address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        T_medical.setToolTipText("");
        T_medical.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        T_medical.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        T_medical.setDropMode(javax.swing.DropMode.ON);
        T_medical.setSelectionBackground(new java.awt.Color(0, 0, 0));
        T_medical.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(T_medical);

        staff_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_nameActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Staff ID");

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Staff Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Column Name");

        Owner1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Owner1.setText("Staff Mail");

        Owner2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Owner2.setText("Staff Address");

        ID2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID2.setText("Medical ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(619, 619, 619)
                                .addComponent(sample))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(reset)))
                        .addContainerGap(968, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID)
                                    .addComponent(ID2))
                                .addGap(152, 152, 152)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medical_id, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(staff_id)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Address)
                                    .addComponent(Owner)
                                    .addComponent(Name)
                                    .addComponent(Owner2)
                                    .addComponent(Owner1))
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staff_mail)
                                    .addComponent(staff_address)
                                    .addComponent(staff_mobile)
                                    .addComponent(staff_gender)
                                    .addComponent(staff_name))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(ID1)
                                    .addComponent(jLabel2))
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q_update, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(p_update, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(staff_id1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 163, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(sample)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(q_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ID1)
                                .addComponent(staff_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID)
                            .addComponent(staff_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID2)
                            .addComponent(medical_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Owner))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Owner1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff_address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Owner2))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
            int a = Integer.parseInt(staff_id.getText());
            int b = Integer.parseInt(medical_id.getText());
            
            String c = staff_name.getText();
            String d = staff_gender.getText(); 
            String e = staff_mobile.getText();
            String f = staff_mail.getText();
            String g = staff_address.getText(); 

            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

            Statement st = cn.createStatement();
            st.executeUpdate("insert into staff values("+a+","+b+",'"+c+"','"+d+"','"+e+"','"+f+"','"+g+"')");

            staff_id.setText(null);
            staff_name.setText(null);
            staff_gender.setText(null);
            staff_mobile.setText(null);
            staff_mail.setText(null);
            staff_address.setText(null);
            medical_id.setText(null);

            status_final.setText("Inserted");

            T_medical.setModel(new DefaultTableModel(
                new Object [][] {

                }, new String [] {"staff_id","medical_id", "staff_name", "staff_gender", "staff_mobile","staff_mail","staff_address"}
            ));

                Statement st1 = cn.createStatement();
                String qurry = "select * from staff";
                ResultSet rs = st1.executeQuery(qurry);
                
                while(rs.next()){
                    String staff_id = String.valueOf(rs.getInt("staff_id"));
                    String medical_id = String.valueOf(rs.getInt("medical_id"));
                    String staff_name = String.valueOf(rs.getString("staff_name"));
                    String staff_gender = String.valueOf(rs.getString("staff_gender"));
                    String staff_mobile = String.valueOf(rs.getString("staff_mobile"));
                    String staff_mail = String.valueOf(rs.getString("staff_mail"));
                    String staff_address = String.valueOf(rs.getString("staff_address"));
                    
                    
                    
                    String TBdata[] = {staff_id,medical_id,staff_name,staff_gender,staff_mobile,staff_mail,staff_address};
                    DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                    tb1Model.addRow(TBdata);
            }
            st1.close();

        }

        catch(Exception e){

            status_final.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            int r = Integer.parseInt(staff_id.getText());
            String n = staff_name.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

            Statement st = cn.createStatement();
            st.executeUpdate("delete from staff where staff_id="+r+"");
            
            staff_id.setText(null);
            staff_name.setText(null);
            staff_gender.setText(null);
            staff_mobile.setText(null);
            staff_mail.setText(null);
            staff_address.setText(null);
            medical_id.setText(null);

            status_final.setText("Deleted");

            T_medical.setModel(new DefaultTableModel(
   new Object [][] {

                }, new String [] {"staff_id","medical_id", "staff_name", "staff_gender", "staff_mobile","staff_mail","staff_address"}
            ));

                Statement st1 = cn.createStatement();
                String qurry = "select * from staff";
                ResultSet rs = st1.executeQuery(qurry);
                
                while(rs.next()){
                    String staff_id = String.valueOf(rs.getInt("staff_id"));
                    String medical_id = String.valueOf(rs.getInt("medical_id"));
                    String staff_name = String.valueOf(rs.getString("staff_name"));
                    String staff_gender = String.valueOf(rs.getString("staff_gender"));
                    String staff_mobile = String.valueOf(rs.getString("staff_mobile"));
                    String staff_mail = String.valueOf(rs.getString("staff_mail"));
                    String staff_address = String.valueOf(rs.getString("staff_address"));
                    
                    
                    
                    String TBdata[] = {staff_id,medical_id,staff_name,staff_gender,staff_mobile,staff_mail,staff_address};
                    DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                    tb1Model.addRow(TBdata);
            }
            st1.close();

        }

        catch(Exception e){

            status_final.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        staff_id.setText(null);
        staff_name.setText(null);
        staff_gender.setText(null);
        staff_mobile.setText(null);
        staff_mail.setText(null);
        staff_address.setText(null);
        medical_id.setText(null);
        staff_id1.setText(null);
        p_update.setText(null);
        q_update.setText(null);
        
        status_final.setText(null);

        T_medical.setModel(new DefaultTableModel(
            new Object [][] {

            }, new String [] {"medical_id", "medical_name", "medical_address", "medical_owner"}
        ));
    }//GEN-LAST:event_resetActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            int r = Integer.parseInt(staff_id1.getText());
            String p = p_update.getText();
            String q = q_update.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

            Statement st = cn.createStatement();
            st.executeUpdate("update staff set "+p+"='"+q+"' where staff_id="+r+"");
            staff_id.setText(null);
            p_update.setText(null);
            q_update.setText(null);
            
            status_final.setText("Updated");

            T_medical.setModel(new DefaultTableModel(
                new Object [][] {

                }, new String [] {"staff_id","medical_id", "staff_name", "staff_gender", "staff_mobile","staff_mail","staff_address"}
            ));

            Statement st1 = cn.createStatement();
            String qurry = "select * from staff";
            ResultSet rs = st1.executeQuery(qurry);

            while(rs.next()){
                    String staff_id = String.valueOf(rs.getInt("staff_id"));
                    String medical_id = String.valueOf(rs.getInt("medical_id"));
                    String staff_name = String.valueOf(rs.getString("staff_name"));
                    String staff_gender = String.valueOf(rs.getString("staff_gender"));
                    String staff_mobile = String.valueOf(rs.getString("staff_mobile"));
                    String staff_mail = String.valueOf(rs.getString("staff_mail"));
                    String staff_address = String.valueOf(rs.getString("staff_address"));
                    
                    
                    
                    String TBdata[] = {staff_id,medical_id,staff_name,staff_gender,staff_mobile,staff_mail,staff_address};
                    DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                    tb1Model.addRow(TBdata);
            }
            st1.close();

        }

        catch(Exception e){

            status_final.setText(String.valueOf(e));
        }
    }//GEN-LAST:event_updateActionPerformed

    private void sampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleActionPerformed
        try{

            T_medical.setModel(new DefaultTableModel(
                new Object [][] {

                }, new String [] {"staff_id","medical_id", "staff_name", "staff_gender", "staff_mobile","staff_mail","staff_address"}
            ));

            Class.forName("com.mysql.cj.jdbc.Driver");
            String p1="jdbc:mysql://localhost/miniproject";
            Connection cn = DriverManager.getConnection(p1,"root","01092001");

                Statement st = cn.createStatement();
                String qurry = "select * from staff";
                ResultSet rs = st.executeQuery(qurry);
                
                while(rs.next()){
                    String staff_id = String.valueOf(rs.getInt("staff_id"));
                    String medical_id = String.valueOf(rs.getInt("medical_id"));
                    String staff_name = String.valueOf(rs.getString("staff_name"));
                    String staff_gender = String.valueOf(rs.getString("staff_gender"));
                    String staff_mobile = String.valueOf(rs.getString("staff_mobile"));
                    String staff_mail = String.valueOf(rs.getString("staff_mail"));
                    String staff_address = String.valueOf(rs.getString("staff_address"));
                    
                    
                    
                    String TBdata[] = {staff_id,medical_id,staff_name,staff_gender,staff_mobile,staff_mail,staff_address};
                    DefaultTableModel tb1Model = (DefaultTableModel)T_medical.getModel();
                    tb1Model.addRow(TBdata);
                
            }

        }

        catch(Exception e){

            System.out.print(e);
        }

    }//GEN-LAST:event_sampleActionPerformed

    private void staff_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel ID2;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Owner;
    private javax.swing.JLabel Owner1;
    private javax.swing.JLabel Owner2;
    private javax.swing.JTable T_medical;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField medical_id;
    private javax.swing.JTextField p_update;
    private javax.swing.JTextField q_update;
    private javax.swing.JButton reset;
    private javax.swing.JButton sample;
    private javax.swing.JTextField staff_address;
    private javax.swing.JTextField staff_gender;
    private javax.swing.JTextField staff_id;
    private javax.swing.JTextField staff_id1;
    private javax.swing.JTextField staff_mail;
    private javax.swing.JTextField staff_mobile;
    private javax.swing.JTextField staff_name;
    private javax.swing.JTextArea status_final;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
